### ISSUE TITLE
Error while trying to implement for SST-2

### ISSUE THREAD

**Issue by Graf-D** [HKUNLP/icl-ceil#2]
Hello

I followed your instructions step by step. It is said:
> `run_ceil.sh`: our proposed learning-based retriever. You need to run `run_epr.sh` first to get an initialization for training CEIL.

It worked fine with `for task_name in mrpc` but then I tried to implement your method for the [sst2](https://huggingface.co/datasets/sst2) dataset. I created `sst2.py` based on `icl-ceil/src/dataset_readers/dataset_wrappers/sst5.py` with a few modifications:

```
@field_getter.add("choices")
def get_choices(entry):
    return ["bad", "good"]


class DatasetWrapper(ABC):
    name = "sst2"
    ice_separator = "\n"
    question_field = "sentence"
    answer_field = "label"
    hf_dataset = "sst2"
    hf_dataset_name = None
    field_getter = field_getter
```

Then I ran `run_epr.sh` and got the following error:

```
Error executing job with overrides: ['task_name=sst2', 'dataset_reader.dataset_path=output/epr/sst2/EleutherAI/gpt-neo-2.7B/scored.json', 'index_reader.dataset_path=index_data/sst2/index_dataset.json', 'training_args.output_dir=output/epr/sst2/EleutherAI/gpt-neo-2.7B/bert-fix_ctx-shared-bs64', 'training_args.run_name=bert-fix_ctx-shared-bs64', 'model_config.ctx_model_name=null']
Traceback (most recent call last):
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/training_dsr.py", line 32, in __init__
    self.encoded_dataset = self.encode_field(dataset_wrapper, field)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/training_dsr.py", line 41, in encode_field
    'tokenizer': self.tokenizer}
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/dataset_dict.py", line 871, in map
    for k, dataset in self.items()
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/dataset_dict.py", line 871, in <dictcomp>
    for k, dataset in self.items()
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 578, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2992, in map
    f"Column to remove {list(filter(lambda col: col not in self._data.column_names, remove_columns))} not in the dataset. Current columns in the dataset: {self._data.column_names}"
ValueError: Column to remove ['train', 'validation', 'test'] not in the dataset. Current columns in the dataset: ['idx', 'sentence', 'label']
```

Since sst5 and sst2 have the same structure (both datasets have train, test and validation splits, and each split has idx, sentence/text and label columns), I don't get what's wrong, exactly. How can I fix that?

**Comment by jiacheng-ye** [comment]
Hi, thanks for your question. Could you check whether the dataset is downloaded successfully?

**Comment by Graf-D** [comment]
> Hi, thanks for your question. Could you check whether the dataset is downloaded successfully?

Yes, it is.

Meanwhile, I found a difference that [sst5](https://huggingface.co/datasets/SetFit/sst5/tree/main) files are in jsonl format, and [sst2](https://huggingface.co/datasets/sst2/blob/main/sst2.py) is in tsv files. Could it be important?

Also, where these "columns to remove" even come from? It seems like the problem is [training_dsr.py:40](https://github.com/HKUNLP/icl-ceil/blob/main/src/dataset_readers/training_dsr.py#L40), `dataset_wrapper.field_getter.functions[field]`, which is, if I understand correctly, is basically `dataset_wrappers.sst2.DatasetWrapper["gen_a"]` in my case. Could you please check if my modifications (see the initial message in this issue) are valid? And still, where do these column names appear in the code?

**Comment by jiacheng-ye** [comment]
In my experience, this error may happen when the file doesn't exist. 
Could you check whether `output/epr/sst2/EleutherAI/gpt-neo-2.7B/scored.json` exists? If not, it means some error happens in `scorer.py` in `run_epr.sh`.

**Comment by Graf-D** [comment]
> Could you check whether `output/epr/sst2/EleutherAI/gpt-neo-2.7B/scored.json` exists?

Yep, 44k items:
<img width="744" alt="image" src="https://github.com/HKUNLP/icl-ceil/assets/18219976/3a41b7ec-fbe6-4c4f-882b-3618257dd324">

**Comment by jiacheng-ye** [comment]
Well, could you add some print in`training_dsr.py` to see what the dataset looks like? For example, 
```
    def encode_field(self, dataset_wrapper, field):
        remove_columns = [col for col in dataset_wrapper.dataset.column_names]
        print(remove_columns) ## <---
        print(dataset_wrapper.dataset)  ## <---
        print(dataset_wrapper.dataset[0])  ## <---
        encoded_dataset = dataset_wrapper.dataset.map(
            encode_field,
            load_from_cache_file=False,
            remove_columns=remove_columns,
            fn_kwargs={'field_getter': dataset_wrapper.field_getter.functions[field],
                       'tokenizer': self.tokenizer}
        )
        return encoded_dataset
```

**Comment by Graf-D** [comment]
Actually, I found out that the problem was in base_dsr:
```
Traceback (most recent call last):
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/inference_dsr.py", line 19, in __init__
    self.init_dataset(task_name, field, dataset_path, dataset_split, ds_size, truncation=False)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/base_dsr.py", line 47, in init_dataset
    self.encoded_dataset = encode_field(self.tokenizer, self.dataset_wrapper, field, truncation)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/base_dsr.py", line 31, in encode_field
    'tokenizer': tokenizer, 'truncation': truncation}
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/dataset_dict.py", line 871, in map
    for k, dataset in self.items()
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/dataset_dict.py", line 871, in <dictcomp>
    for k, dataset in self.items()
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 578, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 543, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2992, in map
    f"Column to remove {list(filter(lambda col: col not in self._data.column_names, remove_columns))} not in the dataset. Current columns in the dataset: {self._data.column_names}"
ValueError: Column to remove ['train', 'validation', 'test'] not in the dataset. Current columns in the dataset: ['idx', 'sentence', 'label']
```

But that function looks pretty the same, so I inserted a print you advised, and got the following output:

```
['idx', 'sentence', 'label']
Dataset({
    features: ['idx', 'sentence', 'label'],
    num_rows: 66973
})
{'idx': 0, 'sentence': 'hide new secretions from the parental units ', 'label': 0}
[2023-05-12 15:55:32,829][src.dataset_readers.dataset_wrappers.base_dsw][INFO] - Loading dataset from output/epr/sst2/EleutherAI/gpt-neo-2.7B/retrieved.json, size 44000
['idx', 'sentence', 'label', 'ctxs']
Dataset({
    features: ['idx', 'sentence', 'label', 'ctxs'],
    num_rows: 2156000
})
{'idx': 0, 'sentence': 'a masterpiece ', 'label': 1, 'ctxs': [22333]}
```

Uhhm, can its behaviour somehow not be deterministic? I mean, I literally ran the same command (with pushing an up arrow in the terminal) with no changes except for debug print


UPD: failed later with the following traceback:
```
Traceback (most recent call last):
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/inference_dsr.py", line 19, in __init__
    self.init_dataset(task_name, field, dataset_path, dataset_split, ds_size, truncation=False)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/base_dsr.py", line 50, in init_dataset
    self.encoded_dataset = encode_field(self.tokenizer, self.dataset_wrapper, field, truncation)
  File "/home/lavendermint/distillation/ExamplesSelection/icl-ceil/src/dataset_readers/base_dsr.py", line 27, in encode_field
    print(dataset_wrapper.dataset[0])  ## <---
  File "/home/lavendermint/anaconda3/envs/ceil/lib/python3.7/site-packages/datasets/dataset_dict.py", line 64, in __getitem__
    f"Invalid key: {k}. Please first select a split. For example: "
KeyError: "Invalid key: 0. Please first select a split. For example: `my_dataset_dictionary['train'][0]`. Available splits: ['test', 'train', 'validation']
```
But as long as it's just a debug print, I simply removed it

**Comment by jiacheng-ye** [comment]
Uhhm, so did this problem happen again later? I mean after you remove the `print(dataset_wrapper.dataset[0])`.

**Comment by Graf-D** [comment]
I ended up editing `base_dsr.py` that way:

```
def encode_field(tokenizer, dataset_wrapper, field, truncation):
    try:
        remove_columns = [col for col in dataset_wrapper.dataset["train"].column_names]
        dataset_wrapper.dataset = dataset_wrapper.dataset["train"]
    except:
        remove_columns = [col for col in dataset_wrapper.dataset.column_names]
```

Seems like it works now. Well, at least, it doesn't throw errors anymore.

By the way, what is the difference between `run_ceil.sh` and `run_epr.sh`? Both of them returns accuracy, so I'm a little confused

**Comment by jiacheng-ye** [comment]
Great job!
The main difference between `run_ceil.sh` and `run_epr.sh` is they are running different methods. `run_epr.sh` is the implementation of EPR from this paper https://arxiv.org/abs/2112.08633, which serves as the baseline of our proposed CEIL model (run through `run_ceil.sh`). You can refer to the details in the CEIL paper here https://arxiv.org/abs/2302.05698.

**Comment by Graf-D** [comment]
Oh, I got it now, thank you! It is said "You need to run `run_epr.sh` first to get an initialization for training CEIL" so I thought it implements some part of the CEIL method😅
Thank you for all your answers!
